### PR TITLE
user interaction minor refactoring

### PR DESCRIPTION
**Pull request by Starliyiyu**
- refactored class name of FriendProfileView to DeleteFriendView
 - changed initializations of UserStatusViewModel as David suggested

### CODE REVIEW

**Review by varygx — APPROVED** [review]
Looks good

**Review by wilso16 — DISMISSED** [review]
I saw you deleted the lines in the readme. Remember to add stuff to it later.

**Review by 2368883029 — DISMISSED** [review]
Seems good to me

**Review by varygx — APPROVED** [review]
Looks good, what's the reason for the README change?

**Review by 2368883029 — APPROVED** [review]
Seems good to me

**Review by wilso16 — APPROVED** [review]

**Review by varygx — DISMISSED** [review]

**Review by 2368883029 — APPROVED** [review]
Looks good to me

**Review by dqieu — APPROVED** [review]
llgtm

**Pull request merged**
