### PR TITLE
Feature 9 user management system

### PR DESCRIPTION
**Pull request by 2368883029**
Major Update:
1. Add more documentation for Usecase in register and login
2. Add more testing codes for registering and login
3. Add Testing Tools for tests involving UserDatabase or User entities(detail for documentation)
   1) GenerateTenUserDatabase: generate 10 users into the database
   2) UserDataBaseEraser: erase the database
   3) UserLogTestingTools: Login specific user by given ViewModel
   4) UserRegTestingTools: Register sample Users, including 4 functions for various testing.
   5) UserSecurityQuestionGenerator: Generate Security Question
   6) UserUIInitializer: Initialize User Register and Login UI for Testing purposes
   All Classes above can be found in the test.java.user_unit_test.testing_tools directory
4. Clean Architecture enhancement, now UserCase no longer imports ViewModel.
5. Add UserStatusViewModel under interface_adaptors.user_login_ia *
   This Model includes a) UserName b) password c)user avatar d) account creation time e) friendliest

This means UI(Like UserInteraction and SongAlbrum) can check for logging user Information directly from the UserStatusViewModel, and no longer need to search for the database.

### CODE REVIEW

**Review by wilso16 — APPROVED** [review]
- Some documentation is added but still far from thorough/complete
- Some of the tests do not have the regular JUnit format. Is this intentional?
- I no longer see violating imports after changing return types, well done

**Comment by 2368883029** [comment]
> * Some documentation is added but still far from thorough/complete
> * Some of the tests do not have the regular JUnit format. Is this intentional?
> * I no longer see violating imports after changing return types, well done

The files inside user_unit_test.testing_tools are not testing files, these are testing tools.

**Review by dqieu — APPROVED** [review]
no violation, lgtm

**Review by wilso16 — APPROVED** [review]
- Added documentation for most classes (very few missing) +1
- Issue about JUnit tests have been addressed

**Review by varygx — APPROVED** [review]
Looks like dependencies between IA and ABR were resolved. Boundary classes look good. Tests that cover the use cases are implemented, although they're currently using assert and not the JUnit methods.

**Pull request merged**
