### PR TITLE
Entities Package + QueueEntities

### PR DESCRIPTION
**Pull request by wilso16**
New entities package containing the abstract class record and song (!Need to create a playlist entity and album entity as well!).

QueueEntities contains all the entities required for QueueManager

### CODE REVIEW

**Review by dqieu — DISMISSED** [review]
LGTM

**Review by varygx — APPROVED** [review]
Make sure to add documentation later

**Review by dqieu — COMMENTED** [review]
LGTM

**Review by dqieu — APPROVED** [review]
LGTM

**Review by cynthiaxsa — APPROVED** [review]
Looks solid!

**Pull request merged**
