### PR TITLE
9 feature 7 user interaction system

### PR DESCRIPTION
**Pull request by Starliyiyu**
rearranged packaging for user interaction features

### CODE REVIEW

**Review by wilso16 — APPROVED** [review]
Looks like a bunch of packages were moved around in accordance to our overarching packages. One comment I would like to make about the imports in some of the tests... is there a reason you choose to import classes indivdually rather than using *?

**Comment by Starliyiyu** [comment]
> Looks like a bunch of packages were moved around in accordance to our overarching packages. One comment I would like to make about the imports in some of the tests... is there a reason you choose to import classes indivdually rather than using *?

Nope I simply let Intellij auto imported everything as the packages move around, will fix this if necessary

**Review by cynthiaxsa — APPROVED** [review]
Looks like a good swap into a different packaging format, you have a solid greenlight from me!

**Review by varygx — APPROVED** [review]
LGTM

**Pull request merged**
