### PR TITLE
INTERIM PR clean QueueViewModel and QueueCollectionItem / alt FriendsCollectionButton

### PR DESCRIPTION
**Pull request by fvkxvsop**
added QueueViewModel and QueueCollectionItem. Interim pull request (will add functionality for deleting / rearranging song order in ~1hr)
Please add requestModel and responseModel for Song entities in QueueCollectionItem to be able to access song attributes given the song id.
Also on the side added FriendsCollectionButtonAlt for testing since the last one was overwritten

### CODE REVIEW

**Review by cynthiaxsa — DISMISSED** [review]
looks solid to me

**Review by Starliyiyu — APPROVED** [review]
Queue ia & UI looks good, approve for testing purpposes

**Review by wilso16 — APPROVED** [review]
- Finally, the queue UI. Thank you Alex 👍

**Review by varygx — APPROVED** [review]
UI approved

**Pull request merged**
