### PR TITLE
Attempting to fix out-of-date issues with my branch

### PR DESCRIPTION
**Pull request by cynthiaxsa**

### CODE REVIEW

**Review by Starliyiyu — APPROVED** [review]
Updated packages as intended, for clean architecture issues refer to pr #116

**Review by 2368883029 — APPROVED** [review]
Do we need to approve if we merge something from Main to branch?

**Comment by wilso16** [comment]
You need to fix the conflicts before merging.

**Review by dqieu — APPROVED** [review]
lgtm

**Pull request closed without merging**
