### PR TITLE
Feature 14: Implemented MongoDB for Song Database; implemented SongDA…

### PR DESCRIPTION
**Pull request by varygx**
…O; code clean up for tests, standardized test library to junit4; introduced logging; changed id attributes from int to String; SongDownloader now saves Song object to database

### CODE REVIEW

**Comment by varygx** [comment]
Ignore the failed test, the database is run locally

**Review by cynthiaxsa — DISMISSED** [review]
This all looks solid to me. Also I enjoyed the commenting / documentation throughout. There can never be too much commenting in my opinion, and what you had keeps the reader up to date with what code lines do what exactly, so big thumbs up!

**Review by fvkxvsop — APPROVED** [review]

**Review by dqieu — DISMISSED** [review]
lgtm

**Review by cynthiaxsa — APPROVED** [review]
Oh ok, _now_ it looks good!

**Review by dqieu — APPROVED** [review]
lgtm

**Review by fvkxvsop — APPROVED** [review]

**Pull request merged**
