### PR TITLE
Add User Search and Song Search to ABR package.

### PR DESCRIPTION
**Pull request by zhaolang05**

### CODE REVIEW

**Review by varygx — APPROVED** [review]
LGTM, but need to unify with my SongDAO

**Review by cynthiaxsa — APPROVED** [review]
Looks good to me as well, thought as a documentation person I need to add the obligatory request that you comment through your code when possible to improve its readability for everyone :^)

**Review by dqieu — COMMENTED** [review]
lgtm

**Review by dqieu — APPROVED** [review]
lgtm

**Pull request merged**
