### PR TITLE
TEMP pr

### PR DESCRIPTION
**Pull request by fvkxvsop**
style changes 
changed button functionality

### CODE REVIEW

**Review by varygx — DISMISSED** [review]

**Review by wilso16 — APPROVED** [review]
- I like hte new button to hide queue and reveal queue, one step closer to functionality
- Some updates to the buttons and Main class, just remember TODOs need to be done asap (contact necessary team members)

**Review by Starliyiyu — DISMISSED** [review]

**Review by wilso16 — APPROVED** [review]

**Review by Starliyiyu — DISMISSED** [review]

**Review by cynthiaxsa — APPROVED** [review]
Adjustments including revising the code to rely on the string ids of the songs and playlists instead of the entities itself, looks good as far as I can tell! While it could use more documentation, that can come afterwards at this point.

**Review by wilso16 — APPROVED** [review]
- Final stretch towards functionality, new DTOs for playlist and use case, as well as some much needed changes to QueueCollectionItem.

**Review by 2368883029 — APPROVED** [review]
Add DTO and UI components , seems reasonable to me

**Pull request merged**
