### PR TITLE
79 playlist create impl

### PR DESCRIPTION
**Pull request by dqieu**
-further implementation to co-work

### CODE REVIEW

**Review by wilso16 — DISMISSED** [review]
- Approving so that it can be editted

**Review by wilso16 — DISMISSED** [review]
- Approve to edit

**Review by varygx — APPROVED** [review]
Minor changes to Song and Playlist methods.

**Review by wilso16 — APPROVED** [review]
- Approv edit

**Review by cynthiaxsa — APPROVED** [review]
LGTM

**Pull request merged**
