### PR TITLE
Separated PlaylistDAO into input and output interfaces

### PR DESCRIPTION
**Pull request by varygx**

### CODE REVIEW

**Review by Starliyiyu — APPROVED** [review]
Approve

**Review by cynthiaxsa — APPROVED** [review]
Looks good!

**Review by wilso16 — APPROVED** [review]
Restructing of the SongDAO and creation of default parameters. Nice

**Review by Starliyiyu — APPROVED** [review]
Approve

**Review by cynthiaxsa — APPROVED** [review]
Alrighty, now we're gouda and in business

**Pull request merged**
